version: '3.8'

services:
  api:
    build: .
    container_name: hms_api
    environment:
      - MONGODB_URL=mongodb+srv://akku:akku@cluster0.bsncfq0.mongodb.net/hms_db_1?retryWrites=true&w=majority&appName=Cluster0
      - DATABASE_NAME=hms_db_1
    ports:
      - "8000:8000"
    networks:
      - hms_network

networks:
  hms_network:
    driver: bridge